version: '3'

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: ${CONTAINER_NAME}-app
    ports:
      - '${APP_PORT}:3000'
      - '5555:5555'
      - '9229:9229'
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    build: .docker/postgres
    container_name: ${CONTAINER_NAME}-db
    restart: always
    tty: true
    ports:
      - '${DATABASE_PORT}:5432'
    volumes:
      - .docker/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER='${DATABASE_USER}'
      - POSTGRES_PASSWORD='${DATABASE_PASS}'
      - POSTGRES_DB='${DATABASE_NAME}'
      - POSTGRES_

  pgadmin:
    image: dpage/pgadmin4
    container_name: ${CONTAINER_NAME}-pgadmin
    restart: always
    ports:
      - '5050:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - db
